################################################################
# Global configuration
################################################################

debug = false
checkNewVersion = true
logLevel = "ERROR"



defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true



[retry]

################################################################
# Web configuration backend
################################################################

[web]

# Web administration port.
#
# Required
# Default: ":8080"
#
address = ":8080"




################################################################
# Docker configuration backend
################################################################

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false
swarmmode = false



